DROP TABLE IF EXISTS reserva      CASCADE;
DROP TABLE IF EXISTS emprestimo   CASCADE;
DROP TABLE IF EXISTS copia        CASCADE;
DROP TABLE IF EXISTS obra         CASCADE;
DROP TABLE IF EXISTS funcionario  CASCADE;
DROP TABLE IF EXISTS leitor       CASCADE;
DROP TABLE IF EXISTS pessoa       CASCADE;